public class assetDetail
{
    public string Tag { get; set; }
    public string SubLocationDescription { get; set; }
    public string OfficeTypeDescription { get; set; }
    public string AccountsCatagory { get; set; }
    public string AssetCatDescription { get; set; }
    public string AssetDescription { get; set; }
    public string AssetLocation { get; set; }
    public string PostName { get; set; }
    public string ProjectShortName { get; set; }
    public string OtherIdentification { get; set; }
    public string SerialNo { get; set; }
    public string PreviousTag { get; set; }
    public float costAmount { get; set; }
    public float NetBookAmount { get; set; }
    public string PurchaseDate { get; set; }
    public string IPCRef { get; set; }
    public string AssetCondition { get; set; }
    public bool IsUseable { get; set; }
    public bool IsSurplus { get; set; }
    public bool IsServiceAble { get; set; }
    public bool IsCondemned { get; set; }
    public bool IsMissing { get; set; }
    public string Remarks { get; set; }
    public string CreatedDate { get; set; }
    public string CreatedBy { get; set; }
    public string VehID { get; set; }
    public long UserId { get; set; }
    public long SubLocID { get; set; }
    public long OfficeTypeID { get; set; }
    public long AccountsCatID { get; set; }
    public long AssetNo { get; set; }
    public long AssetCatID { get; set; }
    public long OfficeSecID { get; set; }
    public long PostID { get; set; }
    public long VehicleID { get; set; }
    public long ProjectID { get; set; }
    public long AssetID { get; set; }
    public string OfficeDescription { get; set; }
    public string EDoc { get; set; }
    public string EDoc2 { get; set; }
    public string EDoc3 { get; set; }
    public int TransferID { get; set; }
    public int IsTransfered { get; set; }
    public int BaseRate { get; set; }
    public string DepreciationRule { get; set; }
    public int isCompleted { get; set; }
    public string make { get; set; }
    public string model { get; set; }
    public string size { get; set; }
    public string generation { get; set; }
    public string processor { get; set; }
    public string ram { get; set; }
    public string driveType1 { get; set; }
    public string hd1 { get; set; }
    public string driveType2 { get; set; }
    public string hd2 { get; set; }
    public string vehMake { get; set; }
    public string vehType { get; set; }
    public string vehEngineNum { get; set; }
    public string vehModel { get; set; }
    public string vehChasisNum { get; set; }
    public string mainLocationDescription { get; set; }
    public long MainLocID { get; set; }
    public string author { get; set; }
    public string publisher { get; set; }
    public string volume { get; set; }
    public string edition { get; set; }
    public string pics { get; set; }
}