public class assetWriteOffDetail
{
    public string Name { get; set; }
    public long PostID { get; set; }
    public float EmpLossShare { get; set; }
    public float ValueofLossApproved { get; set; }
    public long WriteOffID { get; set; }
    public string LossDate { get; set; }
    public string DescriptionLoss { get; set; }
    public float ValueofLoss { get; set; }
    public string Remarks { get; set; }
    public float ValueofLossShare { get; set; }
    public long AssetID { get; set; }
    public long Isdeleted { get; set; }
    public long Employeedeleted { get; set; }
    public string AssetDescription { get; set; }
    public string AssetLocation { get; set; }
    public string Tag { get; set; }
    public string PostName { get; set; }
    public float CostAmount { get; set; }
    public float NetBookAmount { get; set; }
    public float RevaluedAmount { get; set; }
    public string PurchaseDate { get; set; }
    public float AccDepreciationonCost { get; set; }
    public float AccDepreciationonRevalued { get; set; }
    public string EDoc { get; set; }
    public string EDoc2 { get; set; }
    public string EDoc3 { get; set; }
    public string VehMake { get; set; }
    public string VehType { get; set; }
    public string VehModel { get; set; }
    public string Make { get; set; }
    public string Model { get; set; }
    public string Size { get; set; }
    public string Generation { get; set; }
    public string Processor { get; set; }
    public string RAM { get; set; }
    public string DriveType1 { get; set; }
    public string HD1 { get; set; }
    public string DriveType2 { get; set; }
    public string HD2 { get; set; }
    public string Author { get; set; }
    public string Publisher { get; set; }
    public string Volume { get; set; }
    public string Edition { get; set; }
    public string OtherIdentification { get; set; }
    public string SerialNo { get; set; }
    public long AssetWriteOffDetail { get; set; }
}