
public class movableAssetReval
{
    public string tag { get; set; }
    public string subLocationDescription { get; set; }
    public string officeTypeDescription { get; set; }
    public string accountsCatagory { get; set; }
    public string assetCatDescription { get; set; }
    public string assetDescription { get; set; }
    public string postName { get; set; }
    public string officeDescription { get; set; }
    public string assetLocation { get; set; }
    public string projectShortName { get; set; }
    public string otherIdentification { get; set; }
    public string serialNo { get; set; }
    public string previousTag { get; set; }
    public string costAmount { get; set; }
    public string PurchaseDate { get; set; }
    public string AssetCondition { get; set; }
    public bool IsUseable { get; set; }
    public bool IsSurplus { get; set; }
    public bool IsServiceAble { get; set; }
    public bool IsCondemned { get; set; }
    public bool IsMissing { get; set; }
    public string Remarks { get; set; }
    public string createdDate { get; set; }
    public string vehID { get; set; }
    public int? subLocID { get; set; }
    public int? officeTypeID { get; set; }
    public int? accountCatID { get; set; }
    public int? assetCatID { get; set; }
    public int? officeSecID { get; set; }
    public int? postID { get; set; }
    public int? vehicleID { get; set; }
    public int? assetID { get; set; }
    public int? netBookAmount { get; set; }
    public string ipcRef { get; set; }
    public string eDoc { get; set; }
    public int? transferID { get; set; }
    public int isTransfered { get; set; }
    public int? baseRate { get; set; }
    public string depriciationRule { get; set; }
    public string createdDateTime { get; set; }
    public int? isDeleted { get; set; }
    public string eDoc2 { get; set; }
    public string eDoc3 { get; set; }
    public string createdBy { get; set; }
    public string modifiedBy { get; set; }
    public string modificationDate { get; set; }
    public int? isCompleted { get; set; }
    public string make { get; set; }
    public string model { get; set; }
    public string size { get; set; }
    public string generation { get; set; }
    public string processor { get; set; }
    public string ram { get; set; }
    public string driveType1 { get; set; }
    public string HD1 { get; set; }
    public string driveType2 { get; set; }
    public string HD2 { get; set; }
    public string vehmake { get; set; }
    public string vehType { get; set; }
    public string vehEngineNum { get; set; }
    public string vehModel { get; set; }
    public string vehChasisNum { get; set; }
    public string finYear { get; set; }
    public float? revaluationAmount { get; set; }
    public string year { get; set; }
    public int? userID { get; set; }
    public string spType { get; set; }
    public string assetDetailID { get; set; }

}