public class roadDetail
{
    public long fixedAssetID { get; set; }
    public long accountsCatID { get; set; }
    public long roadID { get; set; }
    public long projectID { get; set; }
    public long officeSecID { get; set; }
    public long landMeasureTypeID { get; set; }
    public string accountsCatagory { get; set; }
    public string roadShortName { get; set; }
    public string roadName { get; set; }
    public string projectShortName { get; set; }
    public string projectName { get; set; }
    public string officeDescription { get; set; }
    public string landMeasureType { get; set; }
    public string constructionFom { get; set; }
    public string dateofNationalization { get; set; }
    public string constructionTo { get; set; }
    public string remarks { get; set; }
    public string packageName { get; set; }
    public int areaAcquiredKanal { get; set; }
    public int areaAcquiredMarla { get; set; }
    public int areaTransferedKanal { get; set; }
    public long constructionCost { get; set; }
    public long costofLand { get; set; }
    public long openingCost { get; set; }
    public long totalCost { get; set; }
    public long openingRevaluationAmount { get; set; }
    public long openingRevaluationSurplus { get; set; }
    public long totalRevaluationAmount { get; set; }
    public long revaluationSurplus { get; set; }
    public long WDV { get; set; }
    public long AdditionINRevaluationAmount { get; set; }
    public long AdditionINRevaluationSurplus { get; set; }
    public long openingAccDepreciation { get; set; }
    public long accDepreciation { get; set; }
    public long OWDV { get; set; }
    public long roadLength { get; set; }
    public long historicalCost { get; set; }
    public float oProporationforCosttoWDV { get; set; }
    public float proporationforCosttoWDV { get; set; }
    public int areaTransferedMarla { get; set; }
    public int isDeleted { get; set; }
}