public class sudLand
{
    public long AccountsCatID { get; set; }
    public long OfficeSecID { get; set; }
    public long ProjectID { get; set; }
    public long RoadId { get; set; }
    public long BuildingID { get; set; }
    public string DateofNationalization { get; set; }
    public string ConstructionFom { get; set; }
    public string ConstructionTo { get; set; }
    public double ConstructionCost { get; set; }
    public int LandMeasureTypeID { get; set; }
    public float AreaAcquiredKanal { get; set; }
    public float AreaAcquiredMarla { get; set; }
    public float AreaTransferedKanal { get; set; }
    public float AreaTransferedMarla { get; set; }
    public double CostOfLand { get; set; }
    public string Remarks { get; set; }
    public string PurposeofPurchase { get; set; }
    public string PresentUse { get; set; }
    public string PackageName { get; set; }
    public string BridgeName { get; set; }
    public float BridgeLength { get; set; }
    public long FixedAssetID { get; set; }
    public long UserId { get; set; }
    public string SpType { get; set; }
    public string AccountsCatagory { get; set; }
    public string RoadShortName { get; set; }
    public long RoadLength { get; set; }
    public string ProjectShortName { get; set; }
    public string ProjectName { get; set; }
    public string OfficeDescription { get; set; }
    public string LandMeasureType { get; set; }
    public double Openingcost { get; set; }
    public double TotalCost { get; set; }
    public double OpeningRevaluationAmount { get; set; }
    public double OpeningRevaluationSurplus { get; set; }
    public double TotalRevaluationAmount { get; set; }
    public double RevaluationSurplus { get; set; }
    public double WDV { get; set; }
    public double ProporationforCosttoWDV { get; set; }
    public double AdditionINRevaluationAmount { get; set; }
    public double AdditionINRevaluationSurplus { get; set; }
    public double OpeningAccDepreciation { get; set; }
    public double AccDepreciation { get; set; }
    public double OWDV { get; set; }
    public double OProporationforCosttoWDV { get; set; }
    public double historicalCost { get; set; }
    public double Revaluation { get; set; }
    public double AdditioninRevaluation { get; set; }
    public string RoadName { get; set; }
}